### ISSUE TITLE
[🐛 Bug]: Incorrect types for `expect()` when using browser matchers - 'await' has no effect on the type of this expression.

### ISSUE THREAD

**Issue by DJSdev** [webdriverio/expect-webdriverio#791] opened 2022-06-09 19:13 UTC
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

16.14.2

### Mode

WDIO Testrunner

### What happened?

I generated the example project from `npm init wdio .` and I'm using all the default options with the mocha framework in VSCode.

The following code was [taken directly from webdriverio's website](https://webdriver.io/docs/api/expect-webdriverio/#tohaveurlcontaining) and the issue is that VSCode reports `'await' has no effect on the type of this expression.ts(80007)`. This appears to be due to an issue with the typing of `expect` when passing in the browser object. This works fine when an element (`$()`) is passed in.

![image](https://user-images.githubusercontent.com/26153156/172923502-5c144a24-a363-4f7f-aa24-520e205e475a.png)

VSCode offers a "quick fix" that removes the `await`, but the removal of the await causes this to pass no matter if the assertion is correct or not. 

### What is your expected behavior?

I would expect (heh) when using browser matchers with `expect(browser)` WDIO would offer the correct typings so users know that they have to call `await expect()`.

I imagine there are a lot of users who followed VSCode's recommendations and after seeing their tests pass have no reason to go back and check that their assertions are actually working.

### How to reproduce the bug.

Using VSCode, this is an auto-generated spec with an assertion using a browser matcher.

```ts
import LoginPage from  '../pageobjects/login.page';
import SecurePage from '../pageobjects/secure.page';

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await LoginPage.open();

        await LoginPage.login('tomsmith', 'SuperSecretPassword!');

        await expect(SecurePage.flashAlert).toBeExisting();
        await expect(browser).toHaveUrlContaining('/secure'); // VSCode reports the 'await' is unneeded
    });
});
```

### Relevant log output

```typescript
No log output really. If the user follows VSCode suggestion, the spec will **always** pass even if the assertion should fail.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by erwinheitzman** [comment] 2022-06-20 15:08
@praveendvd those are not matchers from the expect-webdriverio library, those are either Mocha or Jasmine matchers and for that reason the message is correct in that the `await` doesn't do anything for it

**Comment by christian-bromann** [comment] 2022-06-20 15:09
Moving the issue into `expect-webdriverio` repository as it relates to the code written here. Right now we enhance the [`expect`](https://www.npmjs.com/package/expect) matchers (or Jasmine ones if you use it) which are all mostly synchronous matchers. We have type definitions for all [added matchers](https://github.com/webdriverio/expect-webdriverio/blob/main/types/expect-webdriverio.d.ts#L63). Maybe instead of just returning the generic `R` like for `toBeDisplayed`:

```ts
        /**
         * `WebdriverIO.Element` -> `isDisplayed`
         */
        toBeDisplayed(options?: ExpectWebdriverIO.CommandOptions): R
```

We should enforce it to be a promise:

```ts
        /**
         * `WebdriverIO.Element` -> `isDisplayed`
         */
        toBeDisplayed(options?: ExpectWebdriverIO.CommandOptions): Promise<R>
```

I am not sure though if this will solve the bug. Any contributions that resolves the bug are highly appreciated. Please take a look into our [contribution guidelines](https://webdriver.io/docs/contribute) and let us know if you have any questions.

**Comment by erwinheitzman** [comment] 2022-06-20 15:10
I was under the same assumption @christian-bromann and you added some nice examples :)

**Comment by christian-bromann** [comment] 2022-08-11 10:42
duplicate of #488

Given we don't need to support sync matchers anymore, this should be an easy one.

**Closed by christian-bromann** 2022-08-11 10:42 UTC
Labels: Bug 🐛, Needs Triaging ⏳
