### ISSUE TITLE
Webdriverio expect typing conflict with jasmine

### ISSUE THREAD

**Issue by Dji75** [webdriverio/expect-webdriverio#915] opened 2022-10-26 13:07 UTC
We use jasmine 4.4.0 in our project and in our unit tests code we encounter typing issue:

```typescript
  expect(...).toHaveBeenCalledOnceWith(...);
```
`toHaveBeenCalledOnceWith` is underlined in red color with the following error:
```
TS2551: Property 'toHaveBeenCalledOnceWith' does not exist on type 'Matchers( (action: V & FunctionIsNotAllowed  void),  (action: V & FunctionIsNotAllowed...>) => void>'. Did you mean 'toHaveBeenNthCalledWith'?
```
Of course, it exists in jasmine (since 4.4), so we looked further...

When looking at type definition for `expect` (in `node_modules/@types/jasmine/index.d.ts`) , we see this :
```
declare function expect<T extends jasmine.Func>(spy: T | jasmine.Spy<T>): jasmine.FunctionMatchers<T>;
```

`expect` is underlined in red color with the following error:
```
TS2451: Cannot redeclare block-scoped variable 'expect'.  jest-global.d.ts(3, 15): 'expect' was also declared here.
```

When looking in `node_modules/expect-webdriverio/types/jest-global.d.ts`, we saw this:
```typescript
declare const expect: ExpectWebdriverIO.Expect

declare namespace NodeJS {
    interface Global {
        expect: ExpectWebdriverIO.Expect;
    }
}
```

Concequently `expect` is redefined globally and overwrite jasmine typing :(

**Comment by Dji75** [comment] 2022-12-07 09:49
Any news on this, please ?

**Comment by Badisi** [comment] 2022-12-12 16:33
I can confirm that this is still an issue in `expect-webdriverio@4.0.1`.

When using Jasmine:
- Async expects are properly recognized as `Jasmine` matchers
- Sync expects are recognized as `ExpectWebdriverIO` matchers 😕

<img width="721" alt="Screen Shot 2022-12-12 at 17 26 56" src="https://user-images.githubusercontent.com/674862/207099164-7ce01db6-2fa2-4137-99ab-b8b7696e9dec.png">

**Comment by Badisi** [comment] 2022-12-17 09:56
Got it working by doing the following:

1. Set [`injectGlobals`](https://webdriver.io/docs/configuration/#injectglobals) to `true` in the wdio configuration file.
   *(so that none of `browser`, `$`, `$$` but also **`expect`** are injected into the global environment)*

   ```ts
   // wdio.conf.ts
   export const config: Options.Testrunner = {
     injectGlobals: false,
     capabilities: ...
   };
   ```

2. Remove `@wdio/globals/types` from `tsconfig.json`
   ```json
   {
     "compilerOptions": {
       "types": [
         "node",
         "expect-webdriverio/jasmine",
         "@wdio/jasmine-framework"
       ]
     }
   }
   ```

4. Explicitly import all the wdio stuff in test files
   ```ts
   import { browser, $, expect as expectWdio } from '@wdio/globals';
   ```

Now `expect` and `expectAsync` will be recognized as Jasmine matchers 🎉

And when I need to use the expect coming from wdio I simply use `expectWdio`.

**Comment by Badisi** [comment] 2022-12-17 10:25
@christian-bromann, thanks for the hint on this one.

Was it intentional to replace the Jasmine global expect by the wdio one ?

**Comment by christian-bromann** [comment] 2022-12-17 19:59
> Was it intentional to replace the Jasmine global expect by the wdio one ?

We maintained interoperability between the matchers but decided to move away from it because it makes maintaining it easier.

**Comment by erwinheitzman** [comment] 2023-09-20 13:31
With the possibility to now manually import the wdio globals I believe this is a great solution for this issue.

What do you think @Dji75 ?

**Comment by christian-bromann** [comment] 2023-09-21 20:18
@erwinheitzman I believe this should work now, since we made a change this year to use Jasmine `expect` when Jasmine is choosen and add our matchers to it. So this issue should be resolved. Can someone confirm?

**Comment by Dji75** [comment] 2023-09-23 13:43
@erwinheitzman thanks for your feedbacks.
Unfortunately, I can't answer for the last wdio releases cause my devops didn't upgrade to v8 versions yet... 😢

**Comment by erwinheitzman** [comment] 2023-09-27 07:22
I have a project in which we use Jest and do not manually import the globals and I have not run into this issue so I am going to close this issue. If anyone does run into issues, feel free to open a new issue 👍

**Closed by erwinheitzman** 2023-09-27 07:22 UTC
Labels: help wanted, Bug 🐛
