### ISSUE TITLE
some bug with 'toBeElementsArrayOfSize' matcher

### ISSUE THREAD

**Issue by pinim** [webdriverio/expect-webdriverio#931] opened 2022-11-09 12:18 UTC
the last night, my nightly tests crashed in a lot of places, the only thing of the crashes is this error
```
TypeError: Cannot read properties of undefined (reading 'parent')
    at getBrowserObject (/node_modules/expect-webdriverio/lib/utils.js:174:23)
    at Object.toBeElementsArrayOfSizeFn (/node_modules/expect-webdriverio/lib/matchers/elements/toBeElementsArrayOfSize.js:21:50)
```
I have not applied any changes to my code in the last week, someone else occurring with the problem?

edit: looks like occurring only in `expect(elemntsArray).toBeElementsArrayOfSize(0)`, in cases i want to validate that the array is totally not in the dom.

**Comment by christian-bromann** [comment] 2022-11-09 17:05
This seems to be related to #925 , cc @DudaGod

**Comment by DudaGod** [comment] 2022-11-09 18:07
Sorry. I will fix it tomorrow (10 november).

**Comment by christian-bromann** [comment] 2022-11-10 17:12
@pinim I just triggered a release with a fix, can you verify if everything is ok again?

**Comment by christian-bromann** [comment] 2022-11-11 18:52
This is fixed in `v3.5.2`

**Closed by christian-bromann** 2022-11-11 18:52 UTC
Labels: help wanted, Bug 🐛

**Comment by christian-bromann** [comment] 2022-11-29 17:32
@pinim can you provide a minimal reproducible example?

**Comment by pinim** [comment] 2022-11-30 09:51
I tried to reproduce it on the wdio `appium-boilerplate` demo app, but there it works, only in my app the error does happen, so maybe it's a specific problem with my app... I will try maybe later to deep investigate it.

**Comment by pinim** [comment] 2022-11-30 09:53
But it's a bit strange the error is mine, isn't it? It looks exactly like the error of the bug that was here

**Comment by pinim** [comment] 2022-11-30 10:13
so, the problem was not related to this fixed bug, but because I'm starting here the discussion I will continue here with the explanation...
I have an assumption that the methode `expect($('selector)).toBeSomthing()` is trying to find the element in the exact state until reaching the `waitfotTimeOut`, so even in the first few seconds the element is not exist, wdio knows to handle the `element not found` error, but in my case, i'm trying to do the same thing but with `expect($$('selector)[0]).toBeSomthing()`, and in this case, if in the first seconds the elements are not existing, the method `$$('...')` returns an empty array, and when I'm trying to do `$$('...')[0].toBeSomthing()` it fails because [0] is undefined. I resolve this by just adding one more expect expression - `await expect($$("UiSelector")).toBeElementsArrayOfSize({gte:1})`.
so, all is good... 😄 
@christian-bromann
