### ISSUE TITLE
Inconsistent api for browser and elements matchers (about global browser)

### ISSUE THREAD

**Issue by Nio-o** [webdriverio/expect-webdriverio#601] opened 2021-11-17 15:37 UTC
Hello. 

I want to ask is there any reason why element matcher takes browser from global, but browser matcher has `browser` as argument of function?

https://github.com/webdriverio/expect-webdriverio/blob/dd3d2c0c5960cc7bedad7894a30508bb79c99e67/src/matchers/browser/toHaveTitle.ts#L4

https://github.com/webdriverio/expect-webdriverio/blob/dd3d2c0c5960cc7bedad7894a30508bb79c99e67/src/matchers/element/toBeDisplayed.ts#L4

I'm using [hermione](https://github.com/gemini-testing/hermione) for running tests. This package allows to run multiple tests at one moment, so there is no global browser. Browser is bounded to `this` of test's `it`

I cannot use element matchers because of browser in global scope, it limits usage of library

It would be nice to have single behaviour for all matchers. May be a can make a pull request to fix it, but I think you have valuable reasons why it is done in this way.

Example of error: 
```
require('expect-webdriverio');

describe('yandex', async function() {
  it('search', async function() {
    await this.browser.url('https://ya.ru/');
    await expect(this.browser.$('#text')).toBeDisplayed()
  });
});


✘ ReferenceError: browser is not defined
at Object.toBeDisplayedFn (C:\work\hermione-example\node_modules\expect-webdriverio\lib\matchers\element\toBeDisplayed.js:8:5)
at Object.runJestExpect (C:\work\hermione-example\node_modules\expect-webdriverio\lib\util\expectAdapter.js:10:15)
at Object.toBeDisplayed (C:\work\hermione-example\node_modules\expect-webdriverio\lib\matchers\element\toBeDisplayed.js:21:38)
at EXTERNAL_MATCHER_TRAP (C:\work\hermione-example\node_modules\expect\build\index.js:386:30)
at Object.throwingMatcher [as toBeDisplayed] (C:\work\hermione-example\node_modules\expect\build\index.js:387:15)
at Object. (C:\work\hermione-example\tests\desktop\test_jc.js:13:47)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Thanks in advance

**Comment by Nio-o** [comment] 2021-11-17 15:53
I found similar issue. If you do not have any objections, I can try to make PR, obviously if it will be done without breaking changes 
https://github.com/webdriverio/expect-webdriverio/issues/237

**Comment by christian-bromann** [comment] 2021-11-17 16:04
Let's close and mark as

duplicate of #237

**Closed by christian-bromann** 2021-11-17 16:04 UTC
