### ISSUE TITLE
Unable to compile project in Windows

### ISSUE THREAD

**Issue by suniljaiswal01** [webdriverio/expect-webdriverio#216] opened 2020-09-27 07:07 UTC
I have taken the latest pull from the master branch. I am getting Complication error when i run "npm run build" command.
Could anyone please help me resolve this issue?, i want to start doing contribution to this project.
Below is the screenshot of the issue:

![image](https://user-images.githubusercontent.com/45997477/94358369-1c173000-00be-11eb-9330-532bde3bcf4d.png)

**Comment by mgrybyk** [comment] 2020-09-27 07:26
What is you widows full version?

**Comment by mgrybyk** [comment] 2020-09-27 08:09
Just tested in Microsoft Windows 10 Pro, Version	10.0.19041 Build 19041
`node v12.18.3`
`npm 6.14.8`
works fine.
Closing the issue as far as it's not related to functionality and looks like some Windows environment issue.
Feel free to ask any further questions.

**Comment by suniljaiswal01** [comment] 2020-09-27 10:37
@mgrybyk  Just tested in Microsoft Windows 10 Pro, Version 10.0.15063 Build 15063, but still getting the issue.
Following is the steps i followed:

1. Cloned the project
2. ran npm install command
3. ran npm run build command.

Is there any additional steps that need to be followed?

**Comment by mgrybyk** [comment] 2020-09-27 10:43
Try upgrading Windows. The issue is not related to the expext-webdriverio but to typescript compiler. Look for the answer there.
Make sure you have nodejs 12 or later

**Closed by mgrybyk** 2020-09-27 10:43 UTC
