### ISSUE TITLE
Not working with wdio/allure-reporter

### ISSUE THREAD

**Issue by vbyjsue** [webdriverio/expect-webdriverio#3] opened 2020-01-07 14:22 UTC
Using wdio 5.18.4 and allure-reporter 5.16.6. In case of a failed assertion the allure reporter can not parse the failure message to XML which causes the process to hang indefinitely. 
This is the failure message that can not be handled by allure-js-commons 1.3.2.

[32m- Ditt spel på Bomben [7m(är betal|kostade)[27m[39m
[31m+ Ditt spel på Bomben [7mkostade 16kr[27m[39m
[31m+ [7mDu hittar ditt spel under Mina spel.[27m[39m
[31m+ [7mDu vet väl att du kan stötta din favoritförening varje gång du spelar.[27m[39m
[31m+ [7mVälj föreningar här.[27m[39m

I guess the failure-message ends up formatted in the test object which then is used in all reporters.
While this works for console output, the hidden ESC character makes the xml parsing fail. The colorcoding will also look bad in any other reports.

I'm sorry I don't have any suggestions on how to solve this, but my personal view is that the colorcoding does not add much to the understanding of the failure. Having the expected and actual criterias would give enough information.

**Comment by mgrybyk** [comment] 2020-01-07 19:17
Thanks for submitting, I'll take a look in a week or two

**Comment by lacell75** [comment] 2020-03-20 09:09
I'm waiting the fix also. I have the same bug with characters not allowed in XML, please see logs below :
```Error in "Desktop.Groups.02-Updating a group INQA-234: Updating a group - teardown: Then I expect that "Service Client" is displayed"
Expect $(`desktop-app`).$(`<fn>`).$(`<fn>`).$(`<fn>`).$(`dt-paper-tag*=Service Client`) to be displayed

Expected: "displayed"
Received: "not displayed"
[0-0] Save a screenshot
[0-0] 2020-03-20T09:05:02.669Z ERROR @wdio/runner: Error: charData should not contain characters not allowed in XML
    at XmlCharData.set [as charData] (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\xmlcreate\lib\nodes\XmlCharData.js:75:23)
    at new XmlCharData (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\xmlcreate\lib\nodes\XmlCharData.js:53:24)
    at XmlElement.charData (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\xmlcreate\lib\nodes\XmlElement.js:168:28)
    at parseString (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:53:27)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:227:5)
    at parseObjectOrMapEntry (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseObjectOrMapEntry (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:220:9)
    at C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:192:9
    at Array.forEach (<anonymous>)
    at parseArrayOrSet (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:187:16)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:224:9)
    at parseObjectOrMapEntry (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseObjectOrMapEntry (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:132:5)
    at parseObjectOrMap (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:152:13)
    at parseValue (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:220:9)
    at parseToDocument (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:249:5)
    at Object.parse (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\js2xmlparser\lib\main.js:265:20)
    at Object.writeSuite (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\allure-js-commons\writer.js:9:83)
    at Allure.endSuite (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\allure-js-commons\index.js:36:16)
    at AllureReporter.onSuiteEnd (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\@wdio\allure-reporter\build\index.js:111:17)
    at AllureReporter.<anonymous> (C:\Users\fcellier\Documents\02-Test_Auto\end-to-end-tests-wdio5\node_modules\@wdio\reporter\build\index.js:149:12)
    at AllureReporter.emit (events.js:203:13)
[0-0] Error: charData should not contain characters not allowed in XML```

**Comment by christian-bromann** [comment] 2020-03-20 16:55
Duplicate of webdriverio/webdriverio#5038

**Closed by christian-bromann** 2020-03-20 16:55 UTC
Labels: bug
